/**
 * End-to-end TRANSPORT / POLICY check against the real service.
 *
 * Starts service/ on a free port, then drives the REAL ProducerConnection and GameAdapter
 * classes over real WebSockets / HTTP. Observations are SYNTHETIC ObservationBody values
 * (simulated: true) generated by this script: this checks transport, ordering, dedup,
 * replay and the policy wiring. It says nothing about camera or vision accuracy.
 *
 * Run from web/:  node scripts/integration-check.ts   (or: npm run integration)
 * Exit code 0 only if every scenario passes.
 */

import { spawn } from 'node:child_process'
import type { ChildProcess } from 'node:child_process'
import { createServer } from 'node:net'
import { fileURLToPath } from 'node:url'
import WebSocket from 'ws'
import type { ConnectionStatusEvent, WebSocketLike } from '../src/transport/contracts.ts'
import type {
  AttentionState,
  CreateSessionResponse,
  Gesture,
  GestureEventMessage,
  ObservationBody,
  SuggestedActionMessage
} from '../src/protocol/types.ts'
import { createSession, deleteSession } from '../src/transport/session.ts'
import { ProducerConnection } from '../src/transport/ProducerConnection.ts'
import { GameAdapter } from '../src/transport/GameAdapter.ts'

const ORIGIN = 'http://localhost:5173'
const SERVICE_DIR = fileURLToPath(new URL('../../service/', import.meta.url))
const PYTHON = fileURLToPath(new URL('../../service/.venv/bin/python', import.meta.url))

// --------------------------------------------------------------------------------------
// Utilities
// --------------------------------------------------------------------------------------

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms))
const now = () => performance.now()

async function waitFor(pred: () => boolean, timeoutMs: number, stepMs = 25): Promise<boolean> {
  const deadline = now() + timeoutMs
  while (now() < deadline) {
    if (pred()) return true
    await sleep(stepMs)
  }
  return pred()
}

function freePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const srv = createServer()
    srv.unref()
    srv.on('error', reject)
    srv.listen(0, '127.0.0.1', () => {
      const addr = srv.address()
      const port = typeof addr === 'object' && addr ? addr.port : 0
      srv.close(() => resolve(port))
    })
  })
}

/** fetch that always carries an allowed Origin, like a browser page on the dev server. */
const originFetch = ((input: Parameters<typeof fetch>[0], init?: Parameters<typeof fetch>[1]) => {
  const headers = new Headers(init?.headers)
  headers.set('Origin', ORIGIN)
  return fetch(input, { ...init, headers })
}) as typeof fetch

/** WebSocket factory using `ws` with an explicit Origin; remembers sockets for sabotage. */
function recordingFactory() {
  const sockets: WebSocket[] = []
  const factory = (url: string): WebSocketLike => {
    const s = new WebSocket(url, { origin: ORIGIN })
    sockets.push(s)
    return s as unknown as WebSocketLike
  }
  return { sockets, factory }
}

// --------------------------------------------------------------------------------------
// Result bookkeeping
// --------------------------------------------------------------------------------------

const results: Array<{ name: string; pass: boolean; detail: string }> = []

function record(name: string, pass: boolean, detail: string): void {
  results.push({ name, pass, detail })
  console.log(`${pass ? 'PASS' : 'FAIL'}  ${name}${detail ? `  — ${detail}` : ''}`)
}

async function scenario(name: string, fn: () => Promise<string>): Promise<void> {
  try {
    const detail = await fn()
    record(name, true, detail)
  } catch (err) {
    record(name, false, err instanceof Error ? err.message : String(err))
  }
}

function assert(cond: unknown, message: string): asserts cond {
  if (!cond) throw new Error(message)
}

// --------------------------------------------------------------------------------------
// Synthetic producer feed (NOT camera data)
// --------------------------------------------------------------------------------------

const m = <T>(value: T) => ({ value, reason: null })

class SyntheticFeed {
  private timer: ReturnType<typeof setInterval> | null = null
  private orientation: 'toward' | 'away' = 'toward'
  private awaySince = 0
  private episode = 0
  private readonly gestureQueue: Array<{ gesture: Gesture; remaining: number }> = []
  private readonly producer: ProducerConnection

  constructor(producer: ProducerConnection) {
    this.producer = producer
  }

  start(intervalMs = 50): void {
    this.timer = setInterval(() => this.producer.submit(this.body()), intervalMs)
  }

  stop(): void {
    if (this.timer) clearInterval(this.timer)
    this.timer = null
  }

  setAway(): void {
    this.orientation = 'away'
    this.episode += 1
    this.awaySince = now()
  }

  setToward(): void {
    this.orientation = 'toward'
  }

  /** Include `gesture` in the next `times` submitted bodies (simulates re-reporting). */
  includeGesture(gesture: Gesture, times: number): void {
    this.gestureQueue.push({ gesture, remaining: times })
  }

  private body(): ObservationBody {
    const t = now()
    const away = this.orientation === 'away'
    const gestures: Gesture[] = []
    for (const q of this.gestureQueue) {
      if (q.remaining > 0) {
        gestures.push(q.gesture)
        q.remaining -= 1
      }
    }
    return {
      capture_ts_ms: t,
      tracking: {
        status: 'tracking',
        valid: true,
        reason: null,
        face_count: 1,
        multiple_faces_visible: false,
        quality: m(0.9)
      },
      calibration: { status: 'calibrated', reason: null, progress: null },
      measurements: {
        head_yaw_deg: m(away ? 40 : 1),
        head_pitch_deg: m(0),
        head_roll_deg: m(0),
        head_facing_score: m(away ? 0.1 : 0.95),
        head_orientation: m(this.orientation),
        head_away_ms: m(away ? Math.round(t - this.awaySince) : 0),
        head_away_episode: this.episode,
        eye_openness_left: m(1),
        eye_openness_right: m(1),
        eye_blink_coefficient_left: m(0.05),
        eye_blink_coefficient_right: m(0.05),
        eyes_closed: m(false),
        eyes_closed_ms: m(0)
      },
      gestures,
      perf: null,
      simulated: true
    }
  }
}

function syntheticGesture(id: string, type: Gesture['type']): Gesture {
  const t = now()
  return {
    gesture_id: id,
    type,
    start_ts_ms: t - 300,
    end_ts_ms: t - 10,
    amplitude_deg: type === 'blink' ? null : 12,
    swings: type === 'blink' ? null : 2
  }
}

/** Game adapter plus everything it reported, for assertions. */
class AdapterProbe {
  readonly adapter: GameAdapter
  readonly sockets: WebSocket[]
  readonly actions: SuggestedActionMessage[] = []
  readonly gestures: GestureEventMessage[] = []
  readonly statuses: ConnectionStatusEvent[] = []
  readonly attentionSeen = new Set<AttentionState>()

  constructor(base: string, session: CreateSessionResponse, sourceId: string) {
    const ws = recordingFactory()
    this.sockets = ws.sockets
    this.adapter = new GameAdapter({
      baseUrl: base,
      sessionId: session.session_id,
      consumerToken: session.consumer_token,
      sourceId,
      webSocketFactory: ws.factory
    })
    this.adapter.onSuggestedAction((a) => this.actions.push(a))
    this.adapter.onGesture((g) => this.gestures.push(g))
    this.adapter.onConnectionStatus((e) => this.statuses.push(e))
    this.adapter.onState((s) => {
      if (s.state) this.attentionSeen.add(s.state.attention_state)
    })
  }

  attention(): AttentionState | null {
    return this.adapter.getLatestState().state?.attention_state ?? null
  }

  count(action: string): number {
    return this.actions.filter((a) => a.action === action).length
  }

  gestureCount(id: string): number {
    return this.gestures.filter((g) => g.gesture.gesture_id === id).length
  }

  uniqueCallbacks(): boolean {
    const a = this.actions.map((x) => x.action_id)
    const g = this.gestures.map((x) => x.gesture.gesture_id)
    return new Set(a).size === a.length && new Set(g).size === g.length
  }
}

function makeProducer(
  base: string,
  session: CreateSessionResponse,
  producerId: string,
  transport: 'websocket' | 'http'
): ProducerConnection {
  return new ProducerConnection({
    baseUrl: base,
    sessionId: session.session_id,
    producerToken: session.producer_token,
    producerId,
    transport,
    sendIntervalMs: 50,
    webSocketFactory: recordingFactory().factory,
    fetchImpl: originFetch
  })
}

// --------------------------------------------------------------------------------------
// Service process
// --------------------------------------------------------------------------------------

async function startService(port: number): Promise<{ proc: ChildProcess; logs: string[] }> {
  const logs: string[] = []
  const proc = spawn(PYTHON, ['-m', 'app'], {
    cwd: SERVICE_DIR,
    env: {
      ...process.env,
      OBS_PORT: String(port),
      OBS_HOST: '127.0.0.1',
      // Keep the policy scenarios fast; all other thresholds are service defaults.
      OBS_POLICY__DELAY_INSTRUCTION_AFTER_MS: '500'
    },
    stdio: ['ignore', 'pipe', 'pipe']
  })
  const keep = (chunk: Buffer) => {
    logs.push(...chunk.toString().split('\n').filter(Boolean))
    if (logs.length > 400) logs.splice(0, logs.length - 400)
  }
  proc.stdout?.on('data', keep)
  proc.stderr?.on('data', keep)
  const base = `http://127.0.0.1:${port}`
  let healthy = false
  const deadline = now() + 20_000
  while (!healthy && now() < deadline && proc.exitCode === null) {
    try {
      healthy = (await fetch(`${base}/health`)).ok
    } catch {
      // not up yet
    }
    if (!healthy) await sleep(100)
  }
  if (!healthy) {
    proc.kill('SIGKILL')
    throw new Error(`service did not become healthy:\n${logs.slice(-30).join('\n')}`)
  }
  return { proc, logs }
}

function stopService(proc: ChildProcess, timeoutMs = 5000): Promise<boolean> {
  if (proc.exitCode !== null || proc.signalCode !== null) return Promise.resolve(true)
  return new Promise((resolve) => {
    const timer = setTimeout(() => {
      proc.kill('SIGKILL')
      resolve(false)
    }, timeoutMs)
    proc.once('exit', () => {
      clearTimeout(timer)
      resolve(true)
    })
    proc.kill('SIGTERM')
  })
}

// --------------------------------------------------------------------------------------
// Scenarios
// --------------------------------------------------------------------------------------

async function run(base: string, proc: ChildProcess): Promise<void> {
  let A: CreateSessionResponse | null = null
  let B: CreateSessionResponse | null = null

  await scenario('create session', async () => {
    A = await createSession(base, { label: 'integration-a', fetchImpl: originFetch })
    B = await createSession(base, { label: 'integration-b', fetchImpl: originFetch })
    assert(A.session_id !== B.session_id, 'session ids collide')
    assert(A.producer_token !== A.consumer_token, 'role tokens must differ')
    assert(A.policy.delay_instruction_after_ms === 500, 'policy override not applied')
    return `sessions ${A.session_id}, ${B.session_id}`
  })
  if (!A || !B) return
  const sa: CreateSessionResponse = A
  const sb: CreateSessionResponse = B

  const adapterA = new AdapterProbe(base, sa, 'game-a')
  const adapterB = new AdapterProbe(base, sb, 'game-b')
  await adapterA.adapter.connect()
  await adapterB.adapter.connect()
  const producerA = makeProducer(base, sa, 'sim-producer-a', 'websocket')
  const producerErrors: string[] = []
  producerA.onError((e) => producerErrors.push(e.code))
  await producerA.connect()
  const feedA = new SyntheticFeed(producerA)
  feedA.start()

  await scenario('state reaches HEAD_TOWARD_SCREEN', async () => {
    const ok = await waitFor(() => adapterA.attention() === 'HEAD_TOWARD_SCREEN', 3000)
    assert(ok, `attention is ${adapterA.attention()}`)
    const s = adapterA.adapter.getLatestState()
    assert(!s.stale && s.state?.vision.simulated === true, 'state should be fresh and flagged simulated')
    return `state_seq=${s.stateSeq}`
  })

  await scenario('gesture resubmitted is delivered once', async () => {
    const g = syntheticGesture('sim-nod-1', 'nod')
    feedA.includeGesture(g, 5)
    const arrived = await waitFor(() => adapterA.gestureCount('sim-nod-1') > 0, 2000)
    assert(arrived, 'gesture never delivered')
    feedA.includeGesture(g, 3) // reported again after it was acked
    await sleep(800)
    const n = adapterA.gestureCount('sim-nod-1')
    assert(n === 1, `delivered ${n} times`)
    assert(producerA.pendingGestureCount === 0, 'gesture still pending at the producer')
    return `delivered once; producer stats ${JSON.stringify(producerA.stats)}`
  })

  await scenario('sustained head-away yields exactly one delay_instruction', async () => {
    const before = adapterA.count('delay_instruction')
    feedA.setAway()
    const got = await waitFor(() => adapterA.count('delay_instruction') > before, 3000)
    assert(got, `no delay_instruction (attention=${adapterA.attention()})`)
    await sleep(1500) // still away: must not repeat
    const n = adapterA.count('delay_instruction') - before
    assert(adapterA.attentionSeen.has('HEAD_AWAY'), 'HEAD_AWAY never observed')
    feedA.setToward()
    assert(n === 1, `got ${n} delay_instruction actions`)
    const a = adapterA.actions.find((x) => x.action === 'delay_instruction')
    assert(a?.source === 'vision', 'delay_instruction should be vision-sourced')
    const back = await waitFor(() => adapterA.attention() === 'HEAD_TOWARD_SCREEN', 2000)
    assert(back, 'did not return to HEAD_TOWARD_SCREEN')
    return `evidence ${JSON.stringify(a?.evidence)}`
  })

  await scenario('task_started + wrong, slowing answers yields offer_hint', async () => {
    const t0 = now()
    const g = adapterA.adapter
    g.sendGameEvent({ event_type: 'task_started', task_id: 'task-1', client_ts_ms: t0 })
    g.sendGameEvent({ event_type: 'answer_submitted', task_id: 'task-1', data: { correct: false }, client_ts_ms: t0 + 1000 })
    g.sendGameEvent({ event_type: 'answer_submitted', task_id: 'task-1', data: { correct: false }, client_ts_ms: t0 + 2100 })
    g.sendGameEvent({ event_type: 'answer_submitted', task_id: 'task-1', data: { correct: false }, client_ts_ms: t0 + 5100 })
    const got = await waitFor(() => adapterA.count('offer_hint') > 0, 3000)
    assert(got, 'no offer_hint')
    const hint = adapterA.actions.find((x) => x.action === 'offer_hint')
    assert(hint?.source === 'gameplay' && hint.task_id === 'task-1', 'offer_hint has wrong source/task')
    assert(await waitFor(() => g.outboxSize === 0, 2000), `outbox not drained (${g.outboxSize})`)
    await sleep(300)
    assert(adapterA.count('offer_hint') === 1, 'offer_hint repeated')
    return `evidence ${JSON.stringify(hint?.evidence)}`
  })

  await scenario('adapter socket terminated: reconnects, replays, no duplicates, outbox acked', async () => {
    const g = adapterA.adapter
    const socketsBefore = adapterA.sockets.length
    const statusesBefore = adapterA.statuses.length
    adapterA.sockets[adapterA.sockets.length - 1].terminate()
    // While the adapter is down: game events queue in the outbox, and a gesture is
    // produced that the service must replay on resume.
    const e1 = g.sendGameEvent({ event_type: 'player_activity', data: { activity: 'typing' } })
    const e2 = g.sendGameEvent({ event_type: 'player_activity', data: { activity: 'clicking' } })
    feedA.includeGesture(syntheticGesture('sim-blink-2', 'blink'), 4)
    const reconnected = await waitFor(
      () => adapterA.sockets.length > socketsBefore && g.status === 'open',
      5000
    )
    assert(reconnected, `adapter did not reconnect (status ${g.status})`)
    const went = adapterA.statuses.slice(statusesBefore).map((e) => `${e.status}:${e.reason}`)
    assert(went.includes('reconnecting:connection_lost'), `unexpected status path ${went.join(',')}`)
    assert(await waitFor(() => g.outboxSize === 0, 3000), `outbox not acked (${g.outboxSize} left)`)
    assert(await waitFor(() => adapterA.gestureCount('sim-blink-2') === 1, 3000), 'replayed gesture missing')
    assert(await waitFor(() => adapterA.attention() === 'HEAD_TOWARD_SCREEN', 2000), 'no fresh state after reconnect')
    await sleep(500)
    assert(adapterA.gestureCount('sim-blink-2') === 1, 'gesture delivered twice')
    assert(adapterA.uniqueCallbacks(), 'duplicate action/gesture callbacks')
    const st = g.stats
    return `events ${e1.slice(0, 8)}…/${e2.slice(0, 8)}… acked; resume_after=${g.lastEventSeq}; acked=${st.eventsAcked} dup=${st.eventsDuplicate}`
  })

  await scenario('HTTP transport producer path', async () => {
    const C = await createSession(base, { label: 'integration-c', fetchImpl: originFetch })
    const adapterC = new AdapterProbe(base, C, 'game-c')
    await adapterC.adapter.connect()
    const producerC = makeProducer(base, C, 'sim-producer-http', 'http')
    await producerC.connect()
    const feedC = new SyntheticFeed(producerC)
    feedC.start()
    feedC.includeGesture(syntheticGesture('sim-http-nod', 'nod'), 3)
    try {
      assert(await waitFor(() => adapterC.attention() === 'HEAD_TOWARD_SCREEN', 3000), `attention ${adapterC.attention()}`)
      assert(await waitFor(() => adapterC.gestureCount('sim-http-nod') === 1, 2000), 'HTTP gesture not delivered')
      await sleep(300)
      assert(adapterC.gestureCount('sim-http-nod') === 1, 'HTTP gesture delivered twice')
      assert(producerC.status === 'open', `producer status ${producerC.status}`)
      assert(producerC.stats.acked > 0, 'no HTTP acks')
      return `producer stats ${JSON.stringify(producerC.stats)}`
    } finally {
      feedC.stop()
      producerC.disconnect()
      adapterC.adapter.disconnect()
      await deleteSession(base, C.session_id, C.producer_token, originFetch).catch(() => {})
    }
  })

  await scenario('second session is isolated', async () => {
    const s = adapterB.adapter.getLatestState()
    assert(s.connection === 'open' && !s.stale, `session B adapter ${s.connection} stale=${s.stale}`)
    assert(s.state?.attention_state === 'UNKNOWN', `session B attention ${s.state?.attention_state}`)
    assert(s.state?.attention_reason === 'no_observations', `session B reason ${s.state?.attention_reason}`)
    assert(adapterB.actions.length === 0 && adapterB.gestures.length === 0, 'session B received A events')
    assert(!adapterB.attentionSeen.has('HEAD_TOWARD_SCREEN') && !adapterB.attentionSeen.has('HEAD_AWAY'), 'B saw vision state')
    return 'UNKNOWN/no_observations, 0 gestures, 0 actions'
  })

  await scenario('stopping the producer makes state UNKNOWN (stale) within 2.5 s', async () => {
    feedA.stop()
    const t0 = now()
    producerA.disconnect()
    const ok = await waitFor(() => adapterA.attention() === 'UNKNOWN', 4000)
    const elapsed = now() - t0
    assert(ok, `attention still ${adapterA.attention()}`)
    const s = adapterA.adapter.getLatestState()
    assert(s.state?.attention_reason === 'stale_observations', `reason ${s.state?.attention_reason}`)
    assert(s.state?.vision.fresh === false && s.state.vision.head_facing_score.value === null, 'stale vision kept values')
    assert(elapsed <= 2500, `took ${Math.round(elapsed)} ms`)
    return `UNKNOWN after ${Math.round(elapsed)} ms`
  })

  await scenario('delete session closes the adapter with a session reason', async () => {
    await deleteSession(base, sa.session_id, sa.consumer_token, originFetch)
    const ok = await waitFor(() => adapterA.adapter.status === 'closed' || adapterA.adapter.status === 'failed', 3000)
    const last = adapterA.statuses[adapterA.statuses.length - 1]
    assert(ok, `adapter status ${adapterA.adapter.status}`)
    assert(last.reason === 'session_closed' || last.reason === 'session_not_found', `reason ${last.reason}`)
    const s = adapterA.adapter.getLatestState()
    assert(s.stale && s.state === null, 'state should be null after close')
    const before = adapterA.sockets.length
    await sleep(1200)
    assert(adapterA.sockets.length === before, 'adapter reconnected after session close')
    return `${last.status}:${last.reason}; producer errors seen: ${producerErrors.length}`
  })

  await scenario('clean shutdown', async () => {
    adapterB.adapter.disconnect()
    await deleteSession(base, sb.session_id, sb.consumer_token, originFetch)
    assert(adapterB.adapter.status === 'closed', 'adapter B not closed')
    const exited = await stopService(proc)
    assert(exited, 'service did not exit on SIGTERM')
    return `service exited (code=${proc.exitCode}, signal=${proc.signalCode})`
  })
}

async function main(): Promise<void> {
  console.log('Integration check: TRANSPORT / POLICY only.')
  console.log('Observations are SYNTHETIC values generated by this script (simulated: true), not camera data.\n')
  const port = await freePort()
  const base = `http://127.0.0.1:${port}`
  let svc: { proc: ChildProcess; logs: string[] } | null = null
  try {
    svc = await startService(port)
    console.log(`service up at ${base} (pid ${svc.proc.pid})\n`)
    await run(base, svc.proc)
  } catch (err) {
    record('harness', false, err instanceof Error ? err.message : String(err))
  } finally {
    if (svc) await stopService(svc.proc)
  }
  const failed = results.filter((r) => !r.pass)
  console.log(`\n${results.length - failed.length}/${results.length} scenarios passed`)
  if (failed.length && svc) {
    console.log('\nLast service log lines:')
    console.log(svc.logs.slice(-25).join('\n'))
  }
  process.exit(failed.length === 0 && results.length > 0 ? 0 : 1)
}

void main()
